"""Stable machine-readable reason codes (API contract: add, never rename; ADR 0009)."""

from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    # Ingest (F1, F4)
    INGEST_PARSE_FAILED = "INGEST_PARSE_FAILED"
    INGEST_FORMAT_UNKNOWN = "INGEST_FORMAT_UNKNOWN"
    INGEST_EMPTY_SOURCE = "INGEST_EMPTY_SOURCE"
    # Validation (F2, F3)
    VALIDATION_FAILED = "VALIDATION_FAILED"
    VALIDATION_PROFILE_INVALID = "VALIDATION_PROFILE_INVALID"
    VALIDATION_RULE_ERROR = "VALIDATION_RULE_ERROR"
    # IO / storage (F9)
    IO_DISK_FULL = "IO_DISK_FULL"
    IO_WRITE_FAILED = "IO_WRITE_FAILED"
    IO_ARTIFACT_MISSING = "IO_ARTIFACT_MISSING"
    RETRYABLE_IO = "RETRYABLE_IO"
    # Jobs (F4-F8, F11)
    IDEMPOTENCY_KEY_CONFLICT = "IDEMPOTENCY_KEY_CONFLICT"
    JOB_NOT_CANCELABLE = "JOB_NOT_CANCELABLE"
    JOB_TIMEOUT = "JOB_TIMEOUT"
    JOB_CANCELED = "JOB_CANCELED"
    WORKER_LOST = "WORKER_LOST"
    # Builds (F14)
    BUILD_SELECTION_EMPTY = "BUILD_SELECTION_EMPTY"
    BUILD_DETERMINISM_MISMATCH = "BUILD_DETERMINISM_MISMATCH"
    # Workloads / GPU (F12)
    GPU_UNAVAILABLE = "GPU_UNAVAILABLE"
    GPU_OOM = "GPU_OOM"
    WORKLOAD_FAILED = "WORKLOAD_FAILED"
    # Generic
    INTERNAL_ERROR = "INTERNAL_ERROR"
