"""Server-rendered UI package for the MVP slice (ADR 0014)."""

from data_engine.web.pages import (
    DEFAULT_THEME,
    THEMES,
    artifacts_fragment,
    artifacts_page,
    episode_detail_page,
    episodes_fragment,
    episodes_page,
    font_bytes,
    insights_fragment,
    insights_page,
    job_detail_page,
    jobs_fragment,
    jobs_page,
    layout_css,
    metrics_fragment,
    metrics_page,
    status_fragment,
    status_page,
    vendor_css,
)

__all__ = [
    "DEFAULT_THEME",
    "THEMES",
    "artifacts_fragment",
    "artifacts_page",
    "episode_detail_page",
    "episodes_fragment",
    "episodes_page",
    "font_bytes",
    "insights_fragment",
    "insights_page",
    "job_detail_page",
    "jobs_fragment",
    "jobs_page",
    "layout_css",
    "metrics_fragment",
    "metrics_page",
    "status_fragment",
    "status_page",
    "vendor_css",
]
